--- # Ansible Playbook to Configure Static Web Server and Use it to Create a new Template.
- hosts: aws
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  vars_files:
  - ../files/awscreds.yml
  tasks:
    - name: Execute All the Installations.
      yum: name={{ item }} state=latest
      with_items:
        - httpd
        - wget
      notify:
        - CopySiteFiles
        - RestartHTTPD
        - WaitForSite
        - TestSite
        - DisplayResults
  handlers:
    - name: CopySiteFiles
      copy: src=../files/index.html dest=/var/www/html/index.html owner=root group=root mode=0655 backup=yes
    - name: RestartHTTPD
      service: name=httpd state=restarted
    - name: WaitForSite
      wait_for: host=ec2-54-213-82-203.us-west-2.compute.amazonaws.com port=80 delay=5
    - name: TestSite
      shell: /usr/bin/wget http://localhost
      register: site_result
    - name: DisplayResults
      debug: var=site_result
- hosts: localhost
  connection: local
  remote_user: ansadm
  become: yes
  gather_facts: no
  vars_files:
  - ../files/awscreds.yml
  tasks:
  - name: Take a snapshot backup of the website directory.
    ec2_snapshot: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-0d7aef1578e4c9d4b
      device_name: /dev/xvda
      description: Initial Playbook Static Site Deployment Backup
      wait: no
    register: snapshot_results
    notify: 
    - DisplaySnapshotResults
    - CreateNewAMI
    - DisplayAMICreationResults
  handlers:
  - name: DisplaySnapshotResults
    debug: var=snapshot_results
  - name: CreateNewAMI
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-0d7aef1578e4c9d4b
      wait: no
      name: myansibleamitemplate111
      tags:
        Name: MyNewAnsibleAMITemplate111
        Service: TestAMIAnsibleTemplate111
    register: ami_result
  - name: DisplayAMICreationResults
    debug: var=ami_result
