--- # Gather EC2 facts from my remote instance(s).
- hosts: aws
  remote_user: ec2-user
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Gather the EC2 facts about running instances.
    action: ec2_facts
  - name: Display the instance type.
    debug: msg='{{ ansible_ec2_instance_type }}'
