--- # EC2 AMI Example for creating a basic AMI template from an existing image.
- hosts: localhost
  connection: local
  remote_user: ansadm
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: More Advance Provisioning of an AMI from our instance.
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-0d7aef1578e4c9d4b
      wait: no
      name: mynewami2
      tags:
       Name: MyNewAMI2
       Service: TestAMIService
      device_mapping:
       - device_name: /dev/sdb1
         size: 100
         delete_on_termination: false
         volume_type: gp2
    register: instance
