--- # EC2 Snapshot Module Example.
- hosts: localhost
  connection: local
  remote_user: ansadm
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Take a snapshot of the running instance root volume.
    ec2_snapshot:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-0d7aef1578e4c9d4b
      device_name: /dev/xvda
      description: Root volume snapshot
      wait: no
    register: snapshot
