--- # EC2 start/stop/terminate Module use example
- hosts: localhost
  connection: local
  remote_user: ansadm
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Manage the state of an instance.
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_ids: i-0a937be39508599b6
      state: running
